INSERT INTO "user" (
    login_id,
    user_name,
    nick_name,
    email,
    password,
    user_role,
    user_status,
    profile_image_url,
    created_at,
    updated_at,
    deleted_at
)
VALUES
     ('login_admin', 'Admin Choe', 'admin_nick', 'admin@example.com', 'password01', 'ADMIN', 'ACTIVE', 'http://example.com/admin.png', NOW(), null, null),
     ('login01', 'User One', 'user01', 'user01@example.com', 'password01', 'USER', 'ACTIVE', 'http://example.com/user01.png', NOW(), null, null),
     ('login02', 'User Two', 'user02', 'user02@example.com', 'password02', 'USER', 'ACTIVE', 'http://example.com/user02.png', NOW(), null, null),
     ('login03', 'User Three', 'user03', 'user03@example.com', 'password03', 'USER', 'ACTIVE', 'http://example.com/user03.png', NOW(), null, null),
     ('login04', 'User Four', 'user04', 'user04@example.com', 'password04', 'USER', 'ACTIVE', 'http://example.com/user04.png', NOW(), null, null),
     ('login05', 'User Five', 'user05', 'user05@example.com', 'password05', 'USER', 'ACTIVE', 'http://example.com/user05.png', NOW(), null, null),
     ('login06', 'User Six', 'user06', 'user06@example.com', 'password06', 'USER', 'ACTIVE', 'http://example.com/user06.png', NOW(), null, null),
     ('login07', 'User Seven', 'user07', 'user07@example.com', 'password07', 'USER', 'ACTIVE', 'http://example.com/user07.png', NOW(), null, null),
     ('login08', 'User Eight', 'user08', 'user08@example.com', 'password08', 'USER', 'ACTIVE', 'http://example.com/user08.png', NOW(), null, null),
     ('login09', 'User Nine', 'user09', 'user09@example.com', 'password09', 'USER', 'ACTIVE', 'http://example.com/user09.png', NOW(), null, null),
     ('login10', 'User Ten', 'user10', 'user10@example.com', 'password10', 'USER', 'ACTIVE', 'http://example.com/user10.png', NOW(), null, null),
     ('login11', 'User Eleven', 'user11', 'user11@example.com', 'password11', 'USER', 'ACTIVE', 'http://example.com/user11.png', NOW(), null, null),
     ('login12', 'User Twelve', 'user12', 'user12@example.com', 'password12', 'USER', 'ACTIVE', 'http://example.com/user12.png', NOW(), null, null),
     ('login13', 'User Thirteen', 'user13', 'user13@example.com', 'password13', 'USER', 'ACTIVE', 'http://example.com/user13.png', NOW(), null, null),
     ('login14', 'User Fourteen', 'user14', 'user14@example.com', 'password14', 'USER', 'ACTIVE', 'http://example.com/user14.png', NOW(), null, null),
     ('login15', 'User Fifteen', 'user15', 'user15@example.com', 'password15', 'USER', 'ACTIVE', 'http://example.com/user15.png', NOW(), null, null),
     ('login16', 'User Sixteen', 'user16', 'user16@example.com', 'password16', 'USER', 'ACTIVE', 'http://example.com/user16.png', NOW(), null, null),
     ('login17', 'User Seventeen', 'user17', 'user17@example.com', 'password17', 'USER', 'ACTIVE', 'http://example.com/user17.png', NOW(), null, null),
     ('login18', 'User Eighteen', 'user18', 'user18@example.com', 'password18', 'USER', 'ACTIVE', 'http://example.com/user18.png', NOW(), null, null),
     ('login19', 'User Nineteen', 'user19', 'user19@example.com', 'password19', 'USER', 'ACTIVE', 'http://example.com/user19.png', NOW(), null, null),
     ('login20', 'User Twenty', 'user20', 'user20@example.com', 'password20', 'USER', 'ACTIVE', 'http://example.com/user20.png', NOW(), null, null),
     ('login21', 'User Twenty-One', 'user21', 'user21@example.com', 'password21', 'USER', 'ACTIVE', 'http://example.com/user21.png', NOW(), null, null),
     ('login22', 'User Twenty-Two', 'user22', 'user22@example.com', 'password22', 'USER', 'ACTIVE', 'http://example.com/user22.png', NOW(), null, null),
     ('login23', 'User Twenty-Three', 'user23', 'user23@example.com', 'password23', 'USER', 'ACTIVE', 'http://example.com/user23.png', NOW(), null, null),
     ('login24', 'User Twenty-Four', 'user24', 'user24@example.com', 'password24', 'USER', 'ACTIVE', 'http://example.com/user24.png', NOW(), null, null),
     ('login25', 'User Twenty-Five', 'user25', 'user25@example.com', 'password25', 'USER', 'ACTIVE', 'http://example.com/user25.png', NOW(), null, null),
     ('login26', 'User Twenty-Six', 'user26', 'user26@example.com', 'password26', 'USER', 'ACTIVE', 'http://example.com/user26.png', NOW(), null, null),
     ('login27', 'User Twenty-Seven', 'user27', 'user27@example.com', 'password27', 'USER', 'ACTIVE', 'http://example.com/user27.png', NOW(), null, null),
     ('login28', 'User Twenty-Eight', 'user28', 'user28@example.com', 'password28', 'USER', 'ACTIVE', 'http://example.com/user28.png', NOW(), null, null),
     ('login29', 'User Twenty-Nine', 'user29', 'user29@example.com', 'password29', 'USER', 'ACTIVE', 'http://example.com/user29.png', NOW(), null, null),
     ('login30', 'User Thirty', 'user30', 'user30@example.com', 'password30', 'USER', 'ACTIVE', 'http://example.com/user30.png', NOW(), null, null),
     ('login31', 'User Thirty-One', 'user31', 'user31@example.com', 'password31', 'USER', 'ACTIVE', 'http://example.com/user31.png', NOW(), null, null),
     ('login32', 'User Thirty-Two', 'user32', 'user32@example.com', 'password32', 'USER', 'ACTIVE', 'http://example.com/user32.png', NOW(), null, null),
     ('login33', 'User Thirty-Three', 'user33', 'user33@example.com', 'password33', 'USER', 'ACTIVE', 'http://example.com/user33.png', NOW(), null, null),
     ('login34', 'User Thirty-Four', 'user34', 'user34@example.com', 'password34', 'USER', 'ACTIVE', 'http://example.com/user34.png', NOW(), null, null),
     ('login35', 'User Thirty-Five', 'user35', 'user35@example.com', 'password35', 'USER', 'ACTIVE', 'http://example.com/user35.png', NOW(), null, null);