-- Disable foreign key checks
SET REFERENTIAL_INTEGRITY FALSE;

-- Truncate the user and post tables
TRUNCATE TABLE "user" RESTART IDENTITY;
TRUNCATE TABLE "post" RESTART IDENTITY;
TRUNCATE TABLE "event" RESTART IDENTITY;
--TRUNCATE TABLE "comment" RESTART IDENTITY;
--TRUNCATE TABLE "alarm" RESTART IDENTITY;
--TRUNCATE TABLE "reaction" RESTART IDENTITY;

-- Re-enable foreign key checks
SET REFERENTIAL_INTEGRITY TRUE;
